#settings:
#  server:
#    port: 8080
#  db:
#    url: jdbc:postgresql://event.surfstudio.ru:5433/hackathon
#    user: postgres
#    pass: postgres5433
settings:
  server:
    port: 8080
  db:
    url: jdbc:sqlite:sqlitesample.db

    user: admin
    pass: admin
